export const ADD_INGREDIENT = 'ADD_INGREDIENT ';
export const INGREDIENT_MIX = 'INGREDIENT_MIX';
export const ADD_BUN = 'ADD_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';